SELECT AUTHOR.author_id,AUTHOR_NAME,CATEGORY,	TOTAL_SALES
FROM
(SELECT AUTHOR_ID, CATEGORY, SUM(SALES) TOTAL_SALES
FROM
(
    SELECT BOOK.book_id,	category,	author_id,	price,	published_date,	SUMS , BOOK.PRICE * S.SUMS AS SALES
FROM BOOK, 
(SELECT BOOK_ID, SUM(SALES) SUMS
FROM BOOK_SALES
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=1
GROUP BY BOOK_ID) AS S
WHERE BOOK.BOOK_ID = S.BOOK_ID
) FINAL1
GROUP BY AUTHOR_ID, CATEGORY) FINAL2,
AUTHOR
WHERE FINAL2.AUTHOR_ID = AUTHOR.AUTHOR_ID
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
;