-- 코드를 입력하세요
select FOOD_PRODUCT.CATEGORY, FOOD_PRODUCT.PRICE AS MAX_PRICE, FOOD_PRODUCT.PRODUCT_NAME
from
(select category, max(price) M
FROM FOOD_PRODUCT
WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
GROUP BY CATEGORY) MAXPRICE, FOOD_PRODUCT
where FOOD_PRODUCT.CATEGORY = MAXPRICE.CATEGORY AND FOOD_PRODUCT.PRICE = MAXPRICE.M
ORDER BY FOOD_PRODUCT.PRICE DESC
;